version: "3"

services:
    database:
        image: "postgres:latest"
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - 15432:5432
        env_file:
            - .env
        volumes:
            - ./dbdata/:/var/lib/postgresql/data/
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    laravel:
        image: "serversideup/php:beta-8.3-unit"
        depends_on:
            - database
        environment:
            APP_ENV: local
            PHP_DISPLAY_ERRORS: true
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - 8000:80

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
